### ISSUE TITLE
Bug: Pagination does not work. (Need to fetch 5 issues/PRs per page - recent ones first)

### ISSUE THREAD

**Issue by mehul-m-prajapati** [mehul-m-prajapati/github_tracker#3]
- Also filters of tag, date etc should work for all issues/PRs

**Comment by Git21221** [comment]
@mehul-m-prajapati I can solve

**Comment by yashksaini-coder** [comment]
I want to work on this issue to @mehul-m-prajapati

**Comment by mehul-m-prajapati** [comment]
Okay, work on it and open PR @yashksaini-coder
