### ISSUE TITLE
Add about us, contact us page

### ISSUE THREAD

**Issue by mehul-m-prajapati** [mehul-m-prajapati/github_tracker#6]
Refer :

https://truth-tunnel.vercel.app/

https://scruter.vercel.app/about

**Comment by Abhinav8639** [comment]
"Hello, I would like to work on this task please.

**Comment by mehul-m-prajapati** [comment]
Okay @Abhinav8639 , you can open a PR

**Comment by pulkit1417** [comment]
Hi @mehul-m-prajapati I wanted to work on this PR to add about and contact page

**Comment by mehul-m-prajapati** [comment]
@pulkit1417 : you can still work on it and open PR

**Comment by pulkit1417** [comment]
@mehul-m-prajapati  can you provide some content what should I add in the pages, or should I make a layout only?

**Comment by mehul-m-prajapati** [comment]
@pulkit1417 : add some sample data in the pages 

Refer https://truth-tunnel.vercel.app/
