### ISSUE TITLE
Improve UI/UX of header and footer

### ISSUE THREAD

**Issue by mehul-m-prajapati** [mehul-m-prajapati/github_tracker#8]
Refer:

https://truth-tunnel.vercel.app/

https://ezyshopz.vercel.app/

**Comment by Neeraj9625** [comment]
"Hello, I would like to work on this task please.

**Comment by mehul-m-prajapati** [comment]
yes, you can work on it @Neeraj9625

**Comment by Neeraj9625** [comment]
![Screenshot 2024-11-15 220601](https://github.com/user-attachments/assets/14fee8b4-ada4-41ed-8dfe-b51ed0524d0d)

I've designed a footer with organized sections, and social media links. Does this align with the project’s style and user needs? Are there additional elements or changes you would recommend?"

**Comment by mehul-m-prajapati** [comment]
@Neeraj9625 : open a PR, I will review it there

**Comment by saurabh142003** [comment]
![Screenshot 2024-11-16 233942](https://github.com/user-attachments/assets/f47dfa8e-dba4-4572-999e-ba31fd1da52e)
![Screenshot 2024-11-16 234146](https://github.com/user-attachments/assets/e966dc9c-d092-40c3-816d-15fa5f457c9d)

![Screenshot 2024-11-16 234602](https://github.com/user-attachments/assets/844148a5-a9b5-4822-a90a-58c551f8548b)
1. Created contact page with mobile responsive 
2. Added menu bar in mobile responsive

**Comment by TanishLande** [comment]
I can help you with it in this.

**Comment by Abhinav8639** [comment]
"Hello, I would like to work on this task please.
