### ISSUE TITLE
Add horizontal progress bar on top when any user scrolls down

### ISSUE THREAD

**Issue by mehul-m-prajapati** [mehul-m-prajapati/github_tracker#9]
Add horizontal progress bar on top when any user scrolls down
 
 refer - https://truth-tunnel.vercel.app/

**Comment by nishanthkj** [comment]
I’d like to work on this issue. Could you please provide more details on what needs to be done?

**Comment by mehul-m-prajapati** [comment]
@nishanthkj : You need to add horizontal progress bar on top when any user scrolls down

**Comment by mehul-m-prajapati** [comment]
refer: https://truth-tunnel.vercel.app/

**Comment by nishanthkj** [comment]
Okay, I will work on it.
